package com.king.maillyms.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.king.maillyms.entity.SearchEntity;

import com.king.maillyms.greendao.SearchEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig searchEntityDaoConfig;

    private final SearchEntityDao searchEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        searchEntityDaoConfig = daoConfigMap.get(SearchEntityDao.class).clone();
        searchEntityDaoConfig.initIdentityScope(type);

        searchEntityDao = new SearchEntityDao(searchEntityDaoConfig, this);

        registerDao(SearchEntity.class, searchEntityDao);
    }
    
    public void clear() {
        searchEntityDaoConfig.clearIdentityScope();
    }

    public SearchEntityDao getSearchEntityDao() {
        return searchEntityDao;
    }

}
